### ISSUE TITLE
Could you guys implement $shortrealtobits?

### ISSUE THREAD

**Issue by Devil-SX** [steveicarus/iverilog#1018]
![image](https://github.com/steveicarus/iverilog/assets/77198466/baa37db2-5e32-4b42-bee8-5dfc6e4ee2d3)

**Comment by caryr** [comment]
Do you want the shortreal type and the two translation functions or just the two shortreal translation functions? The translation functions should be relatively easy to implement. Adding the type is significantly more work, but none of it should be that hard.

**Comment by caryr** [comment]
I have added the two functions and they internally use shortreal (float) precision, but the actual shortreal type has not been added.
