### ISSUE TITLE
vpiFullName does not include :: for packages

### ISSUE THREAD

**Issue by toddstrader** [steveicarus/iverilog#1037]
See `37.10`:

> vpiFullName for a package shall be the name of the package and should end with “::”; this syntax disambiguates between a module and a package of the same name.

I'm iterating over `vpiInstance` with v12.0 and can see packages but their names do not include the `::`.

Related to:
https://github.com/cocotb/cocotb/pull/3536

**Comment by caryr** [comment]
Likely a bug since the VPI has not been updated much and lots of changes have happened in language constructs that are supported.

**Comment by caryr** [comment]
We should also check that we can have a package and module with the same name. It's possible we are actually using a common namespace.

**Comment by caryr** [comment]
I have pushed a fix that now emits a :: after a package name whenever vpiFullName is used.
