### ISSUE TITLE
Debian package (apt-get) is 9.7 and contain bugs. Need to release new version of it.

### ISSUE THREAD

**Issue by Dolu1990** [steveicarus/iverilog#108]
I had a strange bug : assign A = (B == C);   return always X.
This bug is not present in 10.0.

(uut drived by cocotb)

**Comment by martinwhitaker** [comment]
We don't provide a Debian package ourselves. You need to contact the Debian package maintainer. I expect the way to do this is to open a ticket in the Debian bug tracker (if there isn't one already).
