### ISSUE TITLE
The sv_parameter_type test hangs

### ISSUE THREAD

**Issue by steveicarus** [steveicarus/iverilog#1083]
This test is marked as NI since it hangs at run time. The test is here: ivtest/ivltests/sv_parameter_type.v

**Comment by caryr** [comment]
This looks like a bug.

**Comment by larsclausen** [comment]
This is the same as #1074. We have a partially driven bit vector and the undriven bits are `'z` instead if `'0` and then we get `'x` as the result of any operation on them.

**Comment by martinwhitaker** [comment]
Fixed in the master branch.
