### ISSUE TITLE
Support implicit named port connections

### ISSUE THREAD

**Issue by shareefj** [steveicarus/iverilog#1107]
Hi,

I've had a search for "implicit port" and nothing came up but I can't believe I'm the first to report this so perhaps my search foo is poor.

Is there any planned support for implicit port connections of the form:

```
modname instname (
  .port
);
```

rather than having to use the regular:

``` modname instname (
  .port (port)
);
```

**Comment by larsclausen** [comment]
This should work when using SystemVerilog mode e.g. `iverilog -g2012`

**Comment by shareefj** [comment]
Thanks. I was using that switch but with v12_0 release.  Should I be using latest main branch?

**Comment by larsclausen** [comment]
This should be support in v12. What is the error message you are getting?

**Comment by martinwhitaker** [comment]
Implicit connections are only allowed for port connections, not for parameter assignments. Closing as invalid.
