### ISSUE TITLE
Segmentation fault caused by null pointer `ranges_` inside `PGModule::dump`

### ISSUE THREAD

**Issue by YikeZhou** [steveicarus/iverilog#1188]
Hi,

I tried to run `ivl` with the `-P <path>` flag. However, I got a segmentation fault when working with [`examples/sqrt.vl`](https://github.com/steveicarus/iverilog/blob/06077ed026b4d8498d9129a6acfb0b44d0b51f18/examples/sqrt.vl).

Here is the backtrace:

```
#0  PGate::dump_ranges (this=this@entry=0x555555898490, out=...) at pform_dump.cc:721
#1  0x000055555573910d in PGModule::dump (this=0x555555898490, out=..., ind=<optimized out>) at pform_dump.cc:826
#2  0x000055555573ff63 in Module::dump (this=<optimized out>, out=...) at pform_dump.cc:1783
#3  0x00005555557401de in pform_dump (out=..., mod=<optimized out>) at pform_dump.cc:1815
#4  0x0000555555605cdc in main (argc=<optimized out>, argv=<optimized out>) at main.cc:1168
```

After investigation, I found that this segmentation fault happened when dumping a `PGModule` object in module `main`. Therefore, I guess this `PGModule` object corresponds to the following line in the module definition:
https://github.com/steveicarus/iverilog/blob/06077ed026b4d8498d9129a6acfb0b44d0b51f18/examples/sqrt.vl#L123

Additionally, `PGModule::dump` doesn't check whether `ranges_` is null before calling the `dump_ranges()` function, resulting in this segmentation fault.
After wrapping `dump_ranges(out);` with `if (is_array()) {...}`, the segmentation fault was eliminated.

https://github.com/steveicarus/iverilog/blob/06077ed026b4d8498d9129a6acfb0b44d0b51f18/pform_dump.cc#L721
https://github.com/steveicarus/iverilog/blob/06077ed026b4d8498d9129a6acfb0b44d0b51f18/pform_dump.cc#L826

**Comment by caryr** [comment]
Fixed in development
