### ISSUE TITLE
No option to run vvp in quiet mode

### ISSUE THREAD

**Issue by pweaverm** [steveicarus/iverilog#1193]
Looking at the options for vvp, I see that there is a -l for the log file, but there isn't a corresponding -quiet that allows the simulation to run without pushing the test case text results to the terminal. This can slow the simulation down for larger sims, is it possible to have a -quiet where only the logfile is updated and not the terminal?

**Comment by martinwhitaker** [comment]
This seems a useful enhancement and shouldn't be too hard to implement. I'll take it on.

**Comment by martinwhitaker** [comment]
This is now implemented in the master branch with the new "-q" flag.

**Comment by pweaverm** [comment]
Hi Martin. I was able to pull the update and verify that the output is quiet with the -q option. Thanks for the quick addition!

One question, what is the background for having the order of the command line options? Why would iverilog or vvp need to have certain options before the code or after? Just curious for my own learning.

Thanks!

**Comment by martinwhitaker** [comment]
> One question, what is the background for having the order of the command line options? Why would iverilog or vvp need to have certain options before the code or after? Just curious for my own learning.

This is better explained in the vvp man page than in the on-line documentation. In short, the options before the file name are interpreted by and affect vvp itself, the options after it are passed on to the executed design and VPI modules.
