### ISSUE TITLE
Windows cross compile under Linux is broken

### ISSUE THREAD

**Issue by udif** [steveicarus/iverilog#136]
Fixed by pull request #135

OK, I lied, this was tested under the Ubuntu 14.04 Windows 10 subsystem :-)
The main problem was due to 3 programs that were  needed for the build process itself, were but were cross-compiled, like the rest of the code.

In addition, the  triplet *-*-mingw32 used in the autoconf.sh file, does not cover only 32 bit as the name implies, but also 64 bit builds. as a result we get errors due to missing __strtod().
The triplet name as defined by the tools is x86_64-w64-mingw32

**Comment by martinwhitaker** [comment]
The pull request was merged.
