### ISSUE TITLE
Unhelpfull error message when parameter expression references undefined parameter

### ISSUE THREAD

**Issue by dieterss** [steveicarus/iverilog#142]
If a parameter is set by an expression which involves a parameter that is not defined, eg.:

parameter y = 1;
parameter a = 0;
//parameter b = 1;

parameter x = y ? a : b;

The compiler aborts with (latest git):
$ iverilog t.v 
t.v:8: assert: elab_expr.cc:5688: failed assertion tru_type == fal_type
Aborted

Which makes it quite difficult to localise the issue.  Full testcase demonstrating the issue is as follows:
--cut--
module test;

parameter y = 1;
parameter a = 0;
//parameter b = 1;

parameter x = y ? a : b;
//parameter x = b;

endmodule
--cut--

Note that if the parameter is set with no expression, i.e.:
parameter x = b;

the compiler is helpfull:
t.v:9: error: Unable to bind parameter `b' in `test'
1 error(s) during elaboration.

**Comment by martinwhitaker** [comment]
Fixed in both the master and v10 branch. Thanks for reporting this.
