### ISSUE TITLE
iverilog-vpi static library search directory

### ISSUE THREAD

**Issue by Gridelen** [steveicarus/iverilog#145]
Static library can be passed to the **iverilog-vpi** using **-l** option. However, I was not able to specify different search directory (like **-L** or **--library-path** option of **ld**). 
Search directory is fixed to `/usr/lib/x86_64-linux-gnu` on my machine which can be examined by **--ldflags**

Is there any way to specify search directory? 
Would such an option be useful?

**Comment by martinwhitaker** [comment]
I've pushed an enhancement to the master branch to support the -L option.

**Comment by martinwhitaker** [comment]
And backported it to the v10 branch.
