### ISSUE TITLE
Numbers in ROM file not separated by blanks are not considered several ones

### ISSUE THREAD

**Issue by piranna** [steveicarus/iverilog#155]
On a ROM file read by `readmemh()` function, if you don't separate hexadecimal values with spaces they are considered a single number. For example, `00000000` is considered a single byte with value zero instead of 4 bytes.

**Comment by martinwhitaker** [comment]
That is correct. The IEEE standard states "White space and/or comments shall be used to separate the numbers." (1364-2005 section 17.2.9). What the standard doesn't say is what should happen if you supply a number that is too large to fit in the memory word. Icarus handles this in the same way as it would handle an assignment (i.e. discarding the excess bits).

**Comment by piranna** [comment]
Shouldn't it throw a warning instead of just silently discard them in both cases?

**Comment by steveicarus** [comment]
I've added a warning in git master.
