### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [steveicarus/iverilog#16]
I would like to point out that identifiers like "[`__PTask_H`](https://github.com/steveicarus/iverilog/blob/6ec31517a9ccdb0e312eeacd24ac38d309a10bf3/PTask.h#L1)" and "[`__nettypes_H`](https://github.com/steveicarus/iverilog/blob/3e95966d704ffb5e39dbe6041f88eab8044db616/nettypes.h)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to reconsider also the use of a prefix like ["`__vpi`" in your source code](https://github.com/steveicarus/iverilog/blob/62abb199d7dfd93524b9b6d410e6422dddbe25f7/vvp/vpi_priv.h#L96 "More update candidates")?

**Comment by steveicarus** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 03/26/2015 02:10 PM, Markus Elfring wrote:
> How do you think about to reconsider also the use of a prefix like 
> "|__vpi|" in your source code 
> <https://github.com/steveicarus/iverilog/blob/62abb199d7dfd93524b9b6d410e6422dddbe25f7/vvp/vpi_priv.h#L96>?

The
> 
specific example of the __vpiHandle class is probably something
that could stand to be changed. If anybody comes up with a patch,
I'd be willing to check it for approval.


- -- 
Steve Williams                "The woods are lovely, dark and deep.
steve at icarus.com           But I have promises to keep,
http://www.icarus.com         and lines to code before I sleep,
http://www.picturel.com       And lines to code before I sleep."
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlUUfPwACgkQrPt1Sc2b3infGwCeK+8Ms5lAFzmkEcFGVWrxw8MD
INgAoOZS8A+YSypStp+XeD4TNhETh/As
=FisT
-----END PGP SIGNATURE-----

**Comment by elfring** [comment]
How do you think about to replace [such a questionable prefix](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Reconsider identifier selection") by [a standard-compliant name space](http://en.cppreference.com/w/cpp/language/namespace "Selection of name scopes")?
