### ISSUE TITLE
Incorrect build instructions for Linux.

### ISSUE THREAD

**Issue by ZiCog** [steveicarus/iverilog#185]
The build instructions for Linux state that one should run configure.sh if building from git.
There is no such script.

I managed to build iverilog with:

    $ git clone git://github.com/steveicarus/iverilog.git
    $ cd iverilog
    $ sh autoconf.sh
    $ ./configure
    $ make
    $ sudo make install

**Comment by ahogen** [comment]
Seems to have been fixed in commit https://github.com/steveicarus/iverilog/commit/fdaf92353237e95de579381f6955862bf608f60e

**Comment by martinwhitaker** [comment]
Yes, it's been fixed.
