### ISSUE TITLE
https://sourceforge.net/tracker/?group_id=149850 doesn't exist

### ISSUE THREAD

**Issue by tommythorn** [steveicarus/iverilog#207]
I just wanted to report a bug.  I spent hours narrowing it down to a bug in Icarus 10.1 and 10.2 (Linux and Mac) and produced a minimal repro case.  The BUGS.txt tells me to research all previous bugs on the above link to see if it already exists, but that link doesn't work (I get a Page not found error).

I'll try to build from git and see if I can reproduce it there.

**Comment by ahogen** [comment]
Was this related to #208?

**Comment by tommythorn** [comment]
I hit this issue (stale URL in BUGS.txt) when I wanted to file #208, so it was coincident but two different issues.

**Comment by martinwhitaker** [comment]
Fixed in both master and v10 branches. Thanks for reporting this.
