### ISSUE TITLE
%c writes nothing if argument equal to 'h0

### ISSUE THREAD

**Issue by eshellko** [steveicarus/iverilog#209]
I am trying to read in BMP file and write it back into another BMP file without modification (this is simplification, original was more complex). But when I write back read values that equal to 8'h0 not written back. As I can see this is due to way vpi/sys_display.c implements "get_format" function. It appends every new variable to already formed string, and if value is 0x0 it just do not add '\0' symbol at the end of string.
Here is the call for argument:
```
      cnt = get_format_char(&result, ljust, plus, ld_zero, width, prec, *cp,
                            info, idx);

```
And here is result processing:
```
      *rtn = realloc(*rtn, (size+cnt)*sizeof(char));
      memcpy(*rtn+size-1, result, cnt);
      free(result);
      size += cnt;
      if (*cp) cp += 1;

```
I've found (but didn't test well) that 'cnt==0' if value of variable for given argument is 8'h0.
So the trick is to add following line after 'get_format_char' call. As even if value is NULL, argument should be written into file (at least in case of binary files).
`   if(cnt == 0) cnt = 1;
`
I've attached associated example. To run, just type 'make example'. 'diff' will return error in case of original Icarus sources. If patch is applied result will be OK. Can any one prove or deny this patch?

[example.tar.gz](https://github.com/steveicarus/iverilog/files/2429434/example.tar.gz)

**Comment by martinwhitaker** [comment]
I've pushed a better fix for this to both the master and v10 branches.
