### ISSUE TITLE
New release is needed

### ISSUE THREAD

**Issue by AlexDaniel** [steveicarus/iverilog#228]
Last iverilog [release](https://github.com/steveicarus/iverilog/releases) was in Aug 2017. Since then there were many improvements (e.g. some absolutely necessary features like #159) which push people to compile from source. I think making a new release will make life easier for a lot of people.

**Comment by TheStr3ak5** [comment]
Package managers do need this. Void linux for example suffers from this problem, and this makes working with iverilog difficult. I could give examples of other distros for what I heard (potentially all? Its difficult to update a package without a named release).

**Comment by martinwhitaker** [comment]
v10.3 is now released.

**Comment by AlexDaniel** [comment]
@martinwhitaker thank you! Missed the debian release a little bit, but better late than never!
