### ISSUE TITLE
mv: cannot stat 'parse.hh': No such file or directory

### ISSUE THREAD

**Issue by fungb** [steveicarus/iverilog#247]
the following error comes up upon make:

mv parse.cc.h parse.h 2>/dev/null || mv parse.hh parse.h
mv: cannot stat 'parse.hh': No such file or directory
Makefile:259: recipe for target 'parse.h' failed
make: *** [parse.h] Error 1

iverilog 10.2
Ubuntu 16.04 LTS on an x86_64
gcc/g++ 9.4
bison 3.4.1
flex 2.6.4
gperf 3.1
make 4.1
autoconf 2.69

**Comment by fungb** [comment]
>

**Comment by martinwhitaker** [comment]
parse.hh should have been automatically generated by bison. Check for errors in the preceding call to bison.
No problem here, using bison 3.3.2

**Comment by martinwhitaker** [comment]
A change in bison was causing this error. I've pushed a fix for this to both the master and the v10 branch. Please test if this fixes the problem for you.

**Comment by fungb** [comment]
confirmed working for /master.

**Comment by cr1901** [comment]
One thing I've noticed is that if you need to for _any_ reason need to _rebuild_ some files (for instance, I was trying to diagnose problems generating PDF files), running `make` again will cause the build to fail with the error described in the issue.

The workaround I've resorted to for now is to remove all `parse.c` files from the build tree every time I need to rebuild to force regeneration of `parse.cc.h`. For whatever reason `parse.hh` is never generated.
