### ISSUE TITLE
Set logging level for FST messages from vvp

### ISSUE THREAD

**Issue by cioma** [steveicarus/iverilog#252]
It would be great to be able to set logging level for FST messages from vvp (e.g. disabling "FST info:" and "FST warning:" messages). Quite often these messages are unnecessary for the designer and bloat vvp output.

**Comment by steveicarus** [comment]
Any examples of warnings that you would like to suppress?

**Comment by steveicarus** [comment]
Lack of response from the reporter, so closing this issue.
