### ISSUE TITLE
Use of "V" as a Makefile variable clashes with common autotools "verbose" meaning, V=1

### ISSUE THREAD

**Issue by StefanBruens** [steveicarus/iverilog#256]
The vpp/Makefile.in uses "V" for holding a list of object files. As GNU autotools uses V=1 for making the build output more verbose, many build systems append "V=1" to the make invocation, overwriting the list.

Possible solutions:
- Use a longer variable name, not clashing with other uses
- Use "override V = ..."

**Comment by martinwhitaker** [comment]
This is really a bug in the build systems - they shouldn't be making assumptions like that. But it's easy enough for us to work around. Done in both master and v10 branches.
