### ISSUE TITLE
Requires a second memory argument (readmemb)

### ISSUE THREAD

**Issue by mickey4u** [steveicarus/iverilog#258]
I am all of a sudden getting requires a second (memory) argument when using $readmemb.
Below is the usage:
`$readmemb("testcases", testvector, 0, 15);`

**Comment by martinwhitaker** [comment]
When reporting bugs, please:
1. Provide a simple but complete test case that reproduces the bug.
2. Report the exact error message, not some paraphrase of it.
The information you have provided suggests `testvector` is not a memory.

**Comment by martinwhitaker** [comment]
No response, so I'm assuming this was a user code error. Feel free to reopen if you can provide a valid test case that demonstrates the problem.
