### ISSUE TITLE
Missing initializer in parse.cc

### ISSUE THREAD

**Issue by RobertBaruch** [steveicarus/iverilog#260]
Warning during compilation (remember, warnings are probably errors!)

```
g++ -DHAVE_CONFIG_H -I. -Ilibmisc  -Wall -Wextra -Wshadow   -g -O2 -MD -c parse.cc -o parse.o
parse.cc:8005:18: warning: missing initializer for member ‘vlltype::text’ [-Wmissing-field-initializers]
   = { 1, 1, 1, 1 }
```

```
g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

**Comment by martinwhitaker** [comment]
This is code that is automatically generated by bison. If we prevent bison generating that code, it also prevents bison generating code to automatically extend the parser stack, causing the parser to fail on complex input code. So I don't think we can avoid this warning. I would be happy to be proved wrong - patches welcome!
