### ISSUE TITLE
Sensitivity list not correctly derived

### ISSUE THREAD

**Issue by philipaxer** [steveicarus/iverilog#277]
Hi All,

The sensitivity list for the following case is not correctly inferred. Changing the wildcard to an explicit list, will yield correct results. The module example_module is needed to trigger the issue.
The toplevel is test_function_sensitivity. Its output ``o`` will stay X, but should evaluate. 

``` systemverilog
`timescale 1ns/1ps

module example_module#
(
    parameter WIDTH=4
)
    (
        input logic [WIDTH-1:0] i,
        output logic [WIDTH-1:0] o
    );
    assign o = i & i; //i must appear twice
endmodule: example_module

module test_function_sensitivity#
(
    parameter WIDTH=4
)
    (
        input logic [WIDTH-1:0] i,
        input logic [WIDTH-1:0] b,
        output logic [WIDTH-1:0] o
    );

    logic [WIDTH-1:0] is;
    logic [WIDTH-1:0] os;

    example_module example(.i(is), .o(os));

    function automatic logic [WIDTH-1:0] f(input logic [WIDTH-1:0] x, logic [WIDTH-1:0] y);
        return x | y;
    endfunction : f

    always @(*) begin : buggy_process //changing this to @(i,os,b) will work
        is = f(i, b);
        o = f(os, b);
    end

endmodule: test_function_sensitivity
```

Testbench:

``` systemverilog
`timescale 1ns/1ps

module test_function_sensivitiy_tb;
    logic [3:0] i, o;
    logic [3:0] b;

    test_function_sensivitiy
    UUT(.*);

    initial begin
        $dumpfile("tb.lxt");
        $dumpvars(0, test_function_sensivitiy_tb);
        i <= 4'b01;
        b <= 4'b0;
        #1;
    end

endmodule
```

**Comment by martinwhitaker** [comment]
This works correctly in v10 (after fixing the typos in the testbench), so is a regression in the devel branch.

**Comment by caryr** [comment]
What version of Icarus are you using?

**Comment by philipaxer** [comment]
The master branch cloned on the day the issue was authored.
Regards
Philip

**Comment by philipaxer** [comment]
The master branch cloned on the day the issue was created. I should have mentioned this.

Regards 
Philip

**Comment by martinwhitaker** [comment]
This was caused by the fix for the compiler hang when a recursive function was called in an always_comb construct. I've pushed a new fix to the master branch. The implementation could be made more efficient - we only really need to reset the set of visited functions at the start of each sensitivity calculation - but that would require more widespread changes.
