### ISSUE TITLE
iverilog-10.3 fails to build with gcc10

### ISSUE THREAD

**Issue by rosset** [steveicarus/iverilog#305]
Full logs here: https://kojipkgs.fedoraproject.org//work/tasks/9478/41319478/build.log

**Comment by martinwhitaker** [comment]
Already fixed in v10-branch. See pull request #302.

**Comment by rosset** [comment]
> Already fixed in v10-branch. See pull request #302.

great, do you plan to make a new release with these fixes or should I cherry pick these commits on top of 10.3 release?
thanks!
