### ISSUE TITLE
Preprocessor Lexer is not keeping track of braces depth level

### ISSUE THREAD

**Issue by antoinea38** [steveicarus/iverilog#309]
The preprocessor does not track braces depth level. It leads to errors when trying to pass arguments containing the "inside" keyword for instance.
```systemverilog
`define TEST_MACRO(arg) ``arg

`TEST_MACRO(signal inside{1, 2});  // error: too many arguments for `TEST_MACRO
```

**Comment by martinwhitaker** [comment]
Fixed in both the master and v10 branches. Thanks for the report.
