### ISSUE TITLE
vpi_handle_by_name does not work for escaped identifiers

### ISSUE THREAD

**Issue by eric-wieser** [steveicarus/iverilog#317]
`vpi_handle_by_name("module.\escaped_signal.with_a_dot")` is not correctly parsed into the path `["module", "escaped_signal.with_a_dot"]`.

These lines are at least partially to blame:

https://github.com/steveicarus/iverilog/blob/a621fa48a6091462e697fba603772b5ed7c4af6b/vvp/vpi_priv.cc#L1357-L1378

Relates to https://sourceforge.net/p/iverilog/mailman/message/22240940/

**Comment by caryr** [comment]
This is now fixed in HEAD for both V10 and development.
