### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by cogzoid** [steveicarus/iverilog#319]
I'm compiling using MINGW64 and it breaks with an error of " undefined reference to `ivl_path_is_parallel'" in /tgt-vlog95/scope.c  Not sure how to proceed past this error.

**Comment by martinwhitaker** [comment]
I always forget that piece of Windows nastiness...
Please test the fix I've just pushed to the master branch.

**Comment by cogzoid** [comment]
That did it!  Thanks for the prompt fix!
