### ISSUE TITLE
VPI: support for bit-selects (vpi_get_handle_by_index())

### ISSUE THREAD

**Issue by cmarqu** [steveicarus/iverilog#323]
It would be nice if bit-selects (``myvector[0]``) could be supported in VPI.
Right now, a message like ``Sorry: Icarus does not currently support vpi_get_handle_by_index() for vpiNet objects (stream_in_data).`` is printed. This is coming from https://github.com/steveicarus/iverilog/blob/40d2a49b90f6a977238f754d3427823917d688a4/vvp/vpi_signal.cc#L684-L688

cocotb tests for this are https://github.com/cocotb/cocotb/blob/master/tests/test_cases/test_discovery/test_discovery.py#L110
and
https://github.com/cocotb/cocotb/blob/master/tests/test_cases/test_discovery/test_discovery.py#L130

**Comment by caryr** [comment]
FYI I have made progress on this. The basic handle by index for a net/reg is working and I'm working on the implementation of the bit functionality. The basic infrastructure for a bit type is in place and I am working on the get and put routines now. I will also need to add the iterators for the bit functionality, but I assume for cocotb you only need the get/put and handle by index so will push those changes once they are complete.

**Comment by cmarqu** [comment]
Thanks very much!

**Comment by caryr** [comment]
I have pushed support for vpi_by_index() of registers/nets to master. There is also support for getting the value from a bit select handle. I still need to work on the ability to put a value and bit iterators are not implemented. The put should print an appropriate message. Please verify that get from a bit handle works as you expect. I will work on put next followed by the iterators.

**Comment by caryr** [comment]
Basic put value is now supported. This may be the last of the functionality you need for this report. Put value is still missing support for force/release and this may be complicated to add. I plan to look at that next. Also, unless scheduling is handled at a higher level, put value delays are not currently supported either.

**Comment by caryr** [comment]
Have you been able to verify if the changes I have committed solve the issues in cocotb?

**Comment by caryr** [comment]
Have you been able to check cocotb works with this change?

**Comment by cmarqu** [comment]
Oops, sorry, I must have accidentally unsubscribed from this issue, so I didn't see your updates.
I'll try to check this over the weekend and let you know.

**Comment by cmarqu** [comment]
Thanks very much for this, I can confirm that the two testcases now run fine.
