### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by themperek** [steveicarus/iverilog#326]
Since there is already a `.travis.yml` in the repository it would beneficial just to enable it to run?

Howto: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

**Comment by martinwhitaker** [comment]
IIUC, only Steve can do this.

**Comment by martinwhitaker** [comment]
But having just looked at a pull request, it looks like it is enabled...

**Comment by themperek** [comment]
Looks not:  https://travis-ci.org/github/steveicarus

**Comment by martinwhitaker** [comment]
Look here: https://travis-ci.com/github/steveicarus/iverilog/builds

With some effort, I've fixed the Windows builds. I've also added a check that the tests produce the expected results, and added the VPI tests.

What seems to be missing from this process is a notification that the CI fails after you push some changes.
