### ISSUE TITLE
Fails to build with GCC 10

### ISSUE THREAD

**Issue by aelmahmoudy** [steveicarus/iverilog#329]
iverilog fails to build with GCC 10, yet it builds with gcc 9.

Full build log can be found at: http://people.debian.org/~doko/logs/gcc10-20200225/iverilog_10.3-1_unstable_gcc10.log

Relevant error follows:

{{{
ld  -r -o libveriuser.o asynch.o delay.o exprinfo.o finish.o getcstringp.o getinstance.o getlongp.o getp.o getsimtime.o io_print.o math.o mc_scan_plusargs.o nodeinfo.o nump.o putlongp.o putp.o spname.o typep.o workarea.o veriusertfs.o priv.o a_close.o a_compare_handles.o a_configure.o a_fetch_argc.o a_fetch_argv.o a_fetch_dir.o a_fetch_fullname.o a_fetch_location.o a_fetch_param.o a_fetch_range.o a_fetch_tfarg.o a_fetch_time.o a_fetch_type.o a_fetch_type_str.o a_fetch_value.o a_handle_by_name.o a_handle_hiconn.o a_handle_object.o a_handle_parent.o a_handle_simulated_net.o a_handle_tfarg.o a_initialize.o a_next.o a_next_bit.o a_next_port.o a_next_topmod.o a_object_of_type.o a_product_version.o a_set_value.o a_vcl.o a_version.o
ld: exprinfo.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: getp.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: getsimtime.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: nodeinfo.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: putp.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: spname.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: veriusertfs.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: priv.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_close.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_configure.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_dir.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_fullname.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_param.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_tfarg.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_time.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_fetch_value.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_handle_by_name.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_handle_hiconn.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_handle_object.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_handle_parent.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_handle_simulated_net.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_next.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_next_bit.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_next_port.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_object_of_type.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
ld: a_vcl.o:./libveriuser/priv.h:34: multiple definition of `pli_trace'; delay.o:./libveriuser/priv.h:34: first defined here
make[2]: *** [Makefile:93: libveriuser.o] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/libveriuser'
make[1]: *** [Makefile:125: all] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
}}}

**Comment by martinwhitaker** [comment]
Already fixed - see #302
