### ISSUE TITLE
Return codes

### ISSUE THREAD

**Issue by DodoB** [steveicarus/iverilog#332]
It appears iverilog does not return a code other than 0. As a result I cannot bail out in a batch or make file if a compile failed. This will then run the simulation on the previous output. This is not a show stopper abut less than ideal and should not be hard to fix.

**Comment by martinwhitaker** [comment]
AFAIK the return codes aren't documented anywhere. Much of the time the value returned is the number of errors reported in the compiler phase that failed, so you can't use it to determine what failed.

**Comment by DodoB** [comment]
Thanks that works. So I must have checked for a specific value, probably 1. I don't remember, that was a while ago. The key is then to simply check for greater than 0.

    On Wednesday, June 10, 2020, 4:05:20 PM PDT, martinwhitaker <notifications@github.com> wrote:  
 
 


AFAIK the return codes aren't documented anywhere. Much of the time the value returned is the number of errors reported in the compiler phase that failed, so you can't use it to determine what failed.
