### ISSUE TITLE
Can set 2-state value to X

### ISSUE THREAD

**Issue by purdeaandrei** [steveicarus/iverilog#337]
See this snippet:

```
module main;

function int bla();
endfunction

int x;

initial begin
    $display("initial x = %d", x);
    $display("trying to force to 'x...");
    x = 'x;
    $display("x = %d", x);
    $display("assigning from function...");
    x = bla();
    $display("x = %d", x);
end
endmodule
```

Results in:
```
initial x =           0
trying to force to 'x...
x =           0
assigning from function...
x =           x
```

SystemVerilog standard says:
"When a 4-state value is automatically converted to a 2-state value, any unknown or high-impedance bits shall be converted to zeros."

**Comment by martinwhitaker** [comment]
Fixed in the master branch. The fix required a change to the VVP input syntax, so cannot be backported to the v10 branch.
