### ISSUE TITLE
Assertion `lval_->more == 0' failed

### ISSUE THREAD

**Issue by klammerj** [steveicarus/iverilog#34]
I've tried to compile this with -tblif
it generates:
> $ iverilog ./tgt2t.v -tblif -dsynth2
> debug: Enable synth2 debug
> ./tgt2t.v:16: NetProcTop::synth_sync: Process is apparently synchronous. Making NetFFs.
> ./tgt2t.v:16: NetEvWait::synth_sync: Synchronous process an event statement.
> ./tgt2t.v:16: NetEvWait::synth_sync: Found and synthesized the FF clock.
>  ivl: synth2.cc:85: virtual bool NetAssignBase::synth_async(Design*, NetScope*, NexusSet&, NetBus&, NetBus&): Assertion `lval_->more == 0' failed.
> sh: line 1:  4168 Done                    /usr/lib/ivl/ivlpp -L -F"/tmp/ivrlg27e788233" -f"/tmp/ivrlg7e788233" -p"/tmp/ivrli7e788233"
>       4169 Aborted                 | /usr/lib/ivl/ivl -C"/tmp/ivrlh7e788233" -C"/usr/lib/ivl/blif.conf" -- -

The code:
```
module pci_tgt(
(*PAD="1"*)
input wire clk,
(*PAD="4"*)
input wire RST,
(*PAD="?"*)
output reg S0,
(*PAD="?"*)
output reg S1,
(*PAD="?"*)
output reg S2);

//the state bits
`define S {S0,S1,S2}

always @(posedge clk or posedge RST)
begin
  if(RST)
  begin
  //this failz an assert....
    `S <= 0;
  end
end

endmodule
```

With the clk removed, it still segfaults(but does not fail the assert). 
What's broken now?

**Comment by caryr** [comment]
See #58 for a discussion of patches that are meant to fix the reset side of this issue. Icarus does not support a D-FF with out a D. That should really be a S/R latch. Example code that is intended to represent this test is attached to #58.

**Comment by klammerj** [comment]
guess I can close this
