### ISSUE TITLE
Specifying empty parameter value with -P crashes iverilog with unhelpful assert fail

### ISSUE THREAD

**Issue by alexforencich** [steveicarus/iverilog#377]
If iverilog is run with an empty parameter setting (e.g. `-P module.PARAM=`), it crashes with a message similar to the following:

    ivl: lexor.lex:1196: verinum* make_unsized_dec(const char*): Assertion `isdigit(*ptr)' failed.
    sh: line 1: 439535 Done                    /usr/lib/ivl/ivlpp -L -F"/tmp/ivrlg217f18491" -f"/tmp/ivrlg17f18491" -p"/tmp/ivrli17f18491"
         439536 Aborted                 (core dumped) | /usr/lib/ivl/ivl -C"/tmp/ivrlh17f18491" -C"/usr/lib/ivl/vvp.conf" -- -

It would be nice to have a more helpful error message instead of a cryptic assert failure (i.e. error: invalid parameter value).

**Comment by martinwhitaker** [comment]
Fixed in both master and v11 branch.
