### ISSUE TITLE
Does iverilog have multi-threading support?

### ISSUE THREAD

**Issue by jakio6** [steveicarus/iverilog#495]
I've googled a little, and there's a thread about multi-threading in 2010, and I did a search in this repo and didn't find things on this topic.
Wish you developers could help ensure this. Thanks.

**Comment by martinwhitaker** [comment]
iverilog is the compiler, which is a single-threaded application. The simulator run-time, vvp, is mostly single-threaded too, although it will use a second thread for waveform dumping.

As was said in the 2010 discussion, making the simulator use multiple threads effectively is a hard task.
