### ISSUE TITLE
Incorrect error "This assignment requires an explicit cast"

### ISSUE THREAD

**Issue by jaminel** [steveicarus/iverilog#498]
When compiling the code below, the error "This assignment requires an explicit cast".  Both source and destination are the same type.

package pkg1;
   
   typedef enum logic [1:0]
     {// Register (in DALU)
      R0     = 2'b00,
      R1     = 2'b01,
      R2     = 2'b10,
      R3     = 2'b11
      } reg_t;

endpackage
   
module test
  (input pkg1::reg_t r1);

   import pkg1::*;
   
   reg_t r2;

   always_comb
     r2 = r1;
   
endmodule // test

**Comment by martinwhitaker** [comment]
As a workaround, declare r2 like this:
````
pkg1::reg_t r2;
````

**Comment by martinwhitaker** [comment]
Fixed in both the master and v11 branch.
