### ISSUE TITLE
Segmentation fault. for 11.0, two lines of code

### ISSUE THREAD

**Issue by armleo** [steveicarus/iverilog#530]
See details here:
https://github.com/armleo/iverilog_seg_fault_0

OS: Ubuntu 21.04 on x86-64 PC.

Do I need to build and run a newer version Iverilog to verify this issue?

**Comment by armleo** [comment]
This issue came up for different source code. Commented out code until this minimum.
Removal of `,` from module a definition fixes this.

While proper error messages are outputted, on source code that I am working on no syntax error message is outputted.

**Comment by martinwhitaker** [comment]
Fixed in both the master and v11 branches.
