### ISSUE TITLE
catch illegal reference to genvar

### ISSUE THREAD

**Issue by zachjs** [steveicarus/iverilog#533]
iverilog (both v11 and the latest master) does not raise an error on the following illegal code.
```SystemVerilog
module top;
    genvar i;
    for (i = 100; i < 101; i = i + 1)
        for (i = 100; i < 101; i = i + 1)
            initial $display("%b %0d", i, $bits(i));
endmodule
```

From Section 12.4.1 of IEEE 1364-2005:
> Because this implicit localparam has the same name as the genvar, any reference to this name inside the loop generate block will be a reference to the localparam, not to the genvar. As a consequence, it is not possible to have two nested loop generate constructs that use the same genvar.

Of course, creating another genvar which shadows the explicit localparam is legal, and this appears to work as expected.

**Comment by martinwhitaker** [comment]
Fixed in both the master and v11 branches.
