### ISSUE TITLE
Warn when initializing output variables

### ISSUE THREAD

**Issue by mcandre** [steveicarus/iverilog#544]
Should iverilog warn when initializing variables used as output parameters?

I'm seeing some indeterminate values that may have been produced by accidentally initializing to one value (a habit from C/C++ programming), but assigning to another value.

**Comment by caryr** [comment]
Can you provide a small example?

**Comment by mcandre** [comment]
Yes, here is an example SystemVerilog for a bad Half Adder implementation that triggers the runtime behavior I'm describing.

https://gist.github.com/mcandre/048436c2630a3ac686529f2363e99d3f#file-half_adder-v-L21-L22

**Comment by caryr** [comment]
Icarus is working as expected for this example. I commented on your code page with more information.
