### ISSUE TITLE
HTTPS for homepage

### ISSUE THREAD

**Issue by mcandre** [steveicarus/iverilog#545]
Can we get SSL certs going for the iverilog homepage?

**Comment by nasciontem** [comment]
If the website already have a valid SSL cert you can redirect the users if they try to access the insecure version of the homepage (via http) to its secure version, with SSL. You have to first check if your host has already suplied the certification to you, if not you need to order it, activate it and then insert on your website a .htaccess file to automate the redirection. 
The .htaccess file will look a lot like this:

<pre><code>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</code></pre>

**Comment by steveicarus** [comment]
The page hosted on github now uses https.
