### ISSUE TITLE
inaccurate assert property implementation

### ISSUE THREAD

**Issue by mcandre** [steveicarus/iverilog#548]
assert property does not appear to emit test failures.

Would be good for vvp to warn about incomplete implementation of `assert property` until that is fixed.

Sometimes, the parser even ignores bad code surrounding assert property statements. For example, I tried `assert property (false);`, and the parser didn't report the bad literal.

**Comment by caryr** [comment]
The compiler should warn about this missing functionality.

**Comment by martinwhitaker** [comment]
Compiling a file containing the line
````
assert property (false);
````
results in the compiler error message
````
test.v:3: sorry: concurrent_assertion_item not supported. Try -gno-assertions or -gsupported-assertions to turn this message off.
````
Please provide a complete example that allows the issue to be reproduced.

**Comment by martinwhitaker** [comment]
No response after more than 6 months, so closing.
