### ISSUE TITLE
task $fmonitor()

### ISSUE THREAD

**Issue by RoninSun** [steveicarus/iverilog#592]
Hello,

When I write testbench and use $fmonitor(), after compiling, it says that "62: task $fmonitor() is not currently implemented."

Are there any solutions that can solve this problem? Or do I need to implement this $fmonitor() by myself?

Thanks

**Comment by steveicarus** [comment]
The $fmonitor  task should be implemented. Please post a small example program, and the steps you are using to try to execute it.

**Comment by steveicarus** [comment]
Issue closed for lack of information.
