### ISSUE TITLE
myhdl co-simulation does not start on Windows -  Unable to find myhdl.vpi.vpi module on the search path

### ISSUE THREAD

**Issue by DavidC-75** [steveicarus/iverilog#606]
This is not a typo - The error message you receive is that `myhdl.vpi.vpi` cannot be found on the search path

The myhdl test insfrastructure is agnostic to the platform you're running on (Linux, Windows).
It always generate a command line like `vvp -v -m ../myhdl.vpi tb_test.o`

But on the receiving end, `vvp` is not agnostic to the platform.

The issue is that in `vvp/vpi_modules.cc`, the routine `vpip_load_module` first tries to determine if the name has at least one directory character in it, where the separation character is platform-dependent:

```
#ifdef __MINGW32__
      const char sep = '\\';
#else
      const char sep = '/';
#endif

      if (strchr(name, sep)) {
```

You might want to consider something more robust, but for now I've just worked around the issue by using two possible separation characters on Windows:

```
      if ((strchr(name, sep))
#ifdef __MINGW32__
          || (strchr(name, '/'))
#endif  
          ) {
```

**Comment by martinwhitaker** [comment]
Fixed in both the master and v11 branches.
