### ISSUE TITLE
SV interface/modport not compiling in Icarus

### ISSUE THREAD

**Issue by svenka3** [steveicarus/iverilog#643]
From test:
  https://github.com/steveicarus/iverilog/blob/master/ivtest/ivltests/sv_interface.v

When I try compiling it as

```sh
iverilog -g2012 sv_interface.v
```
I get an error as below:
```log
sv_interface.v:119: syntax error
sv_interface.v:1: Errors in port declarations.
sv_interface.v:151: syntax error
sv_interface.v:1: Errors in port declarations.
```
Is this a recent breakage or is it unsupported feature?

Thanks

**Comment by martinwhitaker** [comment]
It is an unsupported feature - see issue #464.

**Comment by martinwhitaker** [comment]
Closing as a duplicate.
