### ISSUE TITLE
Missing from installation doc, note on installing bison for Mac

### ISSUE THREAD

**Issue by hughperkins** [steveicarus/iverilog#666]
The installation doc points out need to use bison 3+, not that which is included with Mac. However doing `brew install bison` is not enough to get the new version: have to do something like:

```
export PATH="/usr/local/opt/bison/bin:$PATH"
```

See https://stackoverflow.com/questions/31805431/how-to-install-bison-on-mac-osx for example.

**Comment by martinwhitaker** [comment]
Already documented at https://iverilog.fandom.com/wiki/Installation_Guide#Compiling_on_Macintosh_OS_X.

**Comment by hughperkins** [comment]
Hmmm, right, not sure how I missed that :P
