### ISSUE TITLE
INSTALL file out of date w.r.t README.md, e.g. missing details on running autoconf.sh

### ISSUE THREAD

**Issue by hughperkins** [steveicarus/iverilog#668]
INSTALL file out of date w.r.t README.md, e.g. missing details on running autoconf.sh

Maybe easiest would be to change INSTALL to simply point to the README.md? The README.md seems like the most up to date doc for installation :)

**Comment by DeflateAwning** [comment]
I will take a look and submit a PR

**Comment by DeflateAwning** [comment]
This issue can be closed now

**Comment by martinwhitaker** [comment]
Closing as fixed.
