### ISSUE TITLE
Convert Readme to markdown?

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [steveicarus/iverilog#729]
Would you be interested in having me, or anyone, convert your readme to markdown? 

It would make it more modern and more pleasant to read.

**Comment by steveicarus** [comment]
Most of the documentation has been moved into the Documentation directory as [reStructuredText](http://docutils.sourceforge.net/rst.html) format text. The README is getting pretty obsolete. That said, if you submit a PR to reformat it, I'll gladly entertain it.
