### ISSUE TITLE
When cross-compiling, EXEEXT and BUILD_EXEEXT are mixed up

### ISSUE THREAD

**Issue by giordano** [steveicarus/iverilog#730]
When cross-compiling (for example on Linux for Windows), `EXEEXT` and `BUILD_EXEEXT` are mixed up.  The last definition of `EXEEXT` in the generated `configure` script is
```sh
EXEEXT=$ac_cv_build_exeext
```
which is wrong, because in the Linux -> Windows case `ac_cv_build_exeext` would be the empty string, and so the executables turn out to be without extension, even though higher up in the script there is the right setting
```
EXEEXT=$ac_cv_exeext
```
but this gets overridden without hope.

**Comment by martinwhitaker** [comment]
I believe this was fixed by PR #511. Please reopen if not.
