### ISSUE TITLE
V11: vvp returns exit code zero on VPI error

### ISSUE THREAD

**Issue by punzik** [steveicarus/iverilog#737]
If vvp cannot save the dump file (no rights or no folder exists), it breaks simulation with error `VCD Error: module.v:50: Unable to open module.vcd for output.`, but returns zero as a exit code.
For this reason, automated tools do not understand that an error has occurred.

**Comment by martinwhitaker** [comment]
This was fixed in the development branch 18 months ago. The new behaviour wasn't back-ported to the v11 branch.
