### ISSUE TITLE
Make of tgt-fpga directory fails

### ISSUE THREAD

**Issue by softwarejanitor** [steveicarus/iverilog#738]
Make of tgt-fpga directory fails  Numerous errors when compiling xilinx.c, mostly too many argument errors.

I downloaded the iverilog 12 code from github yesterday.  I'm on Ubuntu 20.04.4 LTS with gcc 9.4.0

$ make
gcc -I. -I..  -DHAVE_CONFIG_H -fPIC -Wall -Wextra -Wshadow -Wstrict-prototypes  -g -O2 -MD -c xilinx.c -o xilinx.o
xilinx.c: In function ‘xilinx_cell_buf’:
xilinx.c:29:45: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   29 | edif_cell_t xilinx_cell_buf(edif_xlibrary_t xlib)
      |                             ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_bufe’:
xilinx.c:40:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   40 | edif_cell_t xilinx_cell_bufe(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_bufg’:
xilinx.c:52:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   52 | edif_cell_t xilinx_cell_bufg(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_buft’:
xilinx.c:63:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   63 | edif_cell_t xilinx_cell_buft(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_ibuf’:
xilinx.c:75:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   75 | edif_cell_t xilinx_cell_ibuf(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_inv’:
xilinx.c:86:45: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   86 | edif_cell_t xilinx_cell_inv(edif_xlibrary_t xlib)
      |                             ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_muxf5’:
xilinx.c:97:47: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
   97 | edif_cell_t xilinx_cell_muxf5(edif_xlibrary_t xlib)
      |                               ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_muxf6’:
xilinx.c:110:47: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  110 | edif_cell_t xilinx_cell_muxf6(edif_xlibrary_t xlib)
      |                               ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_obuf’:
xilinx.c:123:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  123 | edif_cell_t xilinx_cell_obuf(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_lut2’:
xilinx.c:135:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  135 | edif_cell_t xilinx_cell_lut2(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_lut3’:
xilinx.c:147:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  147 | edif_cell_t xilinx_cell_lut3(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_lut4’:
xilinx.c:160:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  160 | edif_cell_t xilinx_cell_lut4(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_fdce’:
xilinx.c:175:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  175 | edif_cell_t xilinx_cell_fdce(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_fdcpe’:
xilinx.c:189:47: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  189 | edif_cell_t xilinx_cell_fdcpe(edif_xlibrary_t xlib)
      |                               ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_fdre’:
xilinx.c:204:46: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  204 | edif_cell_t xilinx_cell_fdre(edif_xlibrary_t xlib)
      |                              ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_mult_and’:
xilinx.c:219:50: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  219 | edif_cell_t xilinx_cell_mult_and(edif_xlibrary_t xlib)
      |                                  ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_muxcy’:
xilinx.c:231:47: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  231 | edif_cell_t xilinx_cell_muxcy(edif_xlibrary_t xlib)
      |                               ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_muxcy_l’:
xilinx.c:244:49: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  244 | edif_cell_t xilinx_cell_muxcy_l(edif_xlibrary_t xlib)
      |                                 ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_cell_xorcy’:
xilinx.c:257:47: warning: declaration of ‘xlib’ shadows a global declaration [-Wshadow]
  257 | edif_cell_t xilinx_cell_xorcy(edif_xlibrary_t xlib)
      |                               ~~~~~~~~~~~~~~~~^~~~
In file included from xilinx.c:21:
generic.h:25:24: note: shadowed declaration is here
   25 | extern edif_xlibrary_t xlib;
      |                        ^~~~
xilinx.c: In function ‘xilinx_common_header’:
xilinx.c:291:16: warning: implicit declaration of function ‘ivl_signal_pins’; did you mean ‘ivl_signal_file’? [-Wimplicit-function-declaration]
  291 |      nports += ivl_signal_pins(sig);
      |                ^~~~~~~~~~~~~~~
      |                ivl_signal_file
xilinx.c:312:36: warning: implicit declaration of function ‘ivl_signal_pin’; did you mean ‘ivl_signal_file’? [-Wimplicit-function-declaration]
  312 |     jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, 0));
      |                                    ^~~~~~~~~~~~~~
      |                                    ivl_signal_file
xilinx.c:312:36: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  312 |     jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, 0));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c:320:25: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  320 |     for (bit = 0 ;  bit < ivl_signal_pins(sig) ; bit += 1) {
      |                         ^
xilinx.c:326:34: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  326 |    jnt = edif_joint_of_nexus(edf,ivl_signal_pin(sig,bit));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c: In function ‘xilinx_show_footer’:
xilinx.c:346:28: warning: implicit declaration of function ‘ivl_const_pins’; did you mean ‘ivl_const_bits’? [-Wimplicit-function-declaration]
  346 |      for (pin = 0 ;  pin < ivl_const_pins(net) ;  pin += 1) {
      |                            ^~~~~~~~~~~~~~
      |                            ivl_const_bits
xilinx.c:346:26: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  346 |      for (pin = 0 ;  pin < ivl_const_pins(net) ;  pin += 1) {
      |                          ^
xilinx.c:350:36: warning: implicit declaration of function ‘ivl_const_pin’; did you mean ‘ivl_const_file’? [-Wimplicit-function-declaration]
  350 |     jnt = edif_joint_of_nexus(edf, ivl_const_pin(net, pin));
      |                                    ^~~~~~~~~~~~~
      |                                    ivl_const_file
xilinx.c:350:36: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  350 |     jnt = edif_joint_of_nexus(edf, ivl_const_pin(net, pin));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c: In function ‘xilinx_show_scope’:
xilinx.c:392:37: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  392 |      jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, 0));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c: In function ‘xilinx_pad’:
xilinx.c:421:27: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  421 |       for (idx = 0 ;  idx < ivl_signal_pins(sig) ;  idx += 1) {
      |                           ^
xilinx.c:437:27: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  437 |       for (idx = 0 ;  idx < ivl_signal_pins(sig) ;  idx += 1) {
      |                           ^
xilinx.c:458:36: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  458 |     jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, idx));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c:471:36: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  471 |     jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, idx));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c:478:36: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  478 |     jnt = edif_joint_of_nexus(edf, ivl_signal_pin(sig, idx));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c: In function ‘xilinx_mux’:
xilinx.c:736:37: error: too many arguments to function ‘ivl_lpm_q’
  736 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_q(net, idx));
      |                                     ^~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1476:20: note: declared here
 1476 | extern ivl_nexus_t ivl_lpm_q(ivl_lpm_t net);
      |                    ^~~~~~~~~
xilinx.c:739:37: warning: implicit declaration of function ‘ivl_lpm_data2’; did you mean ‘ivl_lpm_datab’? [-Wimplicit-function-declaration]
  739 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_data2(net, 0, idx));
      |                                     ^~~~~~~~~~~~~
      |                                     ivl_lpm_datab
xilinx.c:739:37: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  739 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_data2(net, 0, idx));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c:742:37: warning: passing argument 2 of ‘edif_joint_of_nexus’ makes pointer from integer without a cast [-Wint-conversion]
  742 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_data2(net, 1, idx));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
In file included from xilinx.c:20:
edif.h:208:65: note: expected ‘ivl_nexus_t’ {aka ‘struct ivl_nexus_s *’} but argument is of type ‘int’
  208 | extern edif_joint_t edif_joint_of_nexus(edif_t edf, ivl_nexus_t nex);
      |                                                     ~~~~~~~~~~~~^~~
xilinx.c:745:37: error: too many arguments to function ‘ivl_lpm_select’
  745 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_select(net, 0));
      |                                     ^~~~~~~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1482:20: note: declared here
 1482 | extern ivl_nexus_t ivl_lpm_select(ivl_lpm_t net);
      |                    ^~~~~~~~~~~~~~
xilinx.c: In function ‘xilinx_add’:
xilinx.c:780:37: error: too many arguments to function ‘ivl_lpm_q’
  780 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_q(net, 0));
      |                                     ^~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1476:20: note: declared here
 1476 | extern ivl_nexus_t ivl_lpm_q(ivl_lpm_t net);
      |                    ^~~~~~~~~
xilinx.c: In function ‘xilinx_shiftl’:
xilinx.c:856:24: error: too many arguments to function ‘ivl_lpm_select’
  856 |      ivl_nexus_t nex = ivl_lpm_select(net,sdx);
      |                        ^~~~~~~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1482:20: note: declared here
 1482 | extern ivl_nexus_t ivl_lpm_select(ivl_lpm_t net);
      |                    ^~~~~~~~~~~~~~
xilinx.c:925:24: error: too many arguments to function ‘ivl_lpm_q’
  925 |      ivl_nexus_t nex = ivl_lpm_q(net,qdx);
      |                        ^~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1476:20: note: declared here
 1476 | extern ivl_nexus_t ivl_lpm_q(ivl_lpm_t net);
      |                    ^~~~~~~~~
xilinx.c:939:37: error: too many arguments to function ‘ivl_lpm_select’
  939 |      jnt = edif_joint_of_nexus(edf, ivl_lpm_select(net,nsel));
      |                                     ^~~~~~~~~~~~~~
In file included from edif.h:23,
                 from xilinx.c:20:
../ivl_target.h:1482:20: note: declared here
 1482 | extern ivl_nexus_t ivl_lpm_select(ivl_lpm_t net);
      |                    ^~~~~~~~~~~~~~
xilinx.c: In function ‘lut_logic’:
xilinx.c:574:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  574 |      edif_add_to_joint(jnt, lut, LUT_I3);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xilinx.c:575:4: note: here
  575 |    case 4:
      |    ^~~~
xilinx.c:577:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  577 |      edif_add_to_joint(jnt, lut, LUT_I2);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xilinx.c:578:4: note: here
  578 |    case 3:
      |    ^~~~
make: *** [Makefile:75: xilinx.o] Error 1

**Comment by martinwhitaker** [comment]
See #684 in Discussions.
