### ISSUE TITLE
always_ff, always_comb 

### ISSUE THREAD

**Issue by TomO700** [steveicarus/iverilog#744]
Hi,  
I'm getting errors with always_ff, always_comb in icarus. 
Can I please check if these are not yet supported by icarus? 
If there are, what could I be doing wrong?  

Thanks

**Comment by Harnesser** [comment]
Hi there, add the -g2012 to your command line to get support for these

    iverilog -g2012 myfile.v

**Comment by martinwhitaker** [comment]
And make sure you aren't using an old version of iverilog.

**Comment by martinwhitaker** [comment]
Closing as answered. If you still have a problem, please provide a simple test case that allows us to reproduce it. But check #159 and #539 first in case it is a known limitation.
