### ISSUE TITLE
Wrong version syntax in driver-vpi/Makefile.in

### ISSUE THREAD

**Issue by themperek** [steveicarus/iverilog#77]
Command:
```
version.exe '%M,%m,%n,0'
```
generate invalid syntax for windres.
 
Link: https://github.com/steveicarus/iverilog/blob/master/driver-vpi/Makefile.in#L89

**Comment by steveicarus** [comment]
Try changing the command to "version.exe '%M,%n,0,0'" in the driver-vpi/Makefile.in. In the v10 release and new devel, there is no %m string in the version any longer.

Anyhow, if that does it for you, I'll make changes for git master and the v10 branches.

**Comment by themperek** [comment]
This works. 

PS. I would make a pull request but was not sure how this new version should look like.

**Comment by steveicarus** [comment]
Fix pushed into git master and v10-branch.
