### ISSUE TITLE
How to debug iverilog

### ISSUE THREAD

**Issue by WXY9902** [steveicarus/iverilog#791]
Hello, I would like to know how to debug iverilog. Because I didn't find it on the official docs. Can you please give me some help.

**Comment by caryr** [comment]
We will need significantly more information to help you. What issue are you experiencing, do you have a short code example that demonstrates the issue? Also have you enabled warnings? They can provide useful information.

**Comment by WXY9902** [comment]
Sorry, I don't have the corresponding code. I'm just wondering if iverilog has debug mode, can you give me some instructions accordingly.

**Comment by steveicarus** [comment]
This issue is far too vague. Closing. If there is something more specific needed, please create a more detailed issue.
