### ISSUE TITLE
Reverse lookup from vvp_net_t to vpiHandle in vvp?

### ISSUE THREAD

**Issue by wmlye** [steveicarus/iverilog#850]
As mentioned in #848, I'm trying to give `vvp` meaningful warnings when attempting to access elements outside a multi-dimensional packed array.  Reading outside the array, the necessary information has been lost because `%load/vec4` copies the value from a net onto the stack, deleting the information necessary for `%part` to identify the source net.  The copy-on-write mechanism in #849 would alleviate this issue.

However in order to give meaningful warning messages we need to look up the net name from a `vvp_net_t`.  `vvp/words.cc/compile_variable()` takes in the variable/net label and name.  The label is associated with a `vvp_net_t` and is used for all further lookups during compilation, while the name is placed in a `vpiHandle`, which in turn has a pointer to the `vvp_net_t`.  Short of adding a pointer to the `vvp_net_t` structure that points back to the `vpiHandle` is there an already-existing (and efficient) mechanism for finding the `vpiHandle` associated with a given `vvp_net_t`?

**Comment by martinwhitaker** [comment]
Not as far as I'm aware.

A bit late :-( , but closing as answered.
