### ISSUE TITLE
SystemVerilog Type operator not supported

### ISSUE THREAD

**Issue by nikhenri** [steveicarus/iverilog#864]
Hi, 
I'm currently testing icarus.
It seem I have a synthax error each line I used the type() function
Is type supported ? Am i missing something ?

Info:
![image](https://user-images.githubusercontent.com/61157967/213750255-203ba369-6a7f-4e2f-94b5-257ef112db6e.png)

<img width="926" alt="image" src="https://user-images.githubusercontent.com/61157967/213750836-3c6f23a0-4cd8-43d5-9143-a220649b04ec.png">

Thank you :)

**Comment by martinwhitaker** [comment]
Sorry for the slow response. Yes, this is a SystemVerilog feature that is not yet supported.
