### ISSUE TITLE
Error: VVP input file 10.3 can not be run with run time version 13.0 (devel)

### ISSUE THREAD

**Issue by liuyuxivapor** [steveicarus/iverilog#865]
As mentioned above, i installed iveriog v13 but got an error while testing and siming. What should i do to solve or avoid this?

**Comment by liuyuxivapor** [comment]
i mean, how to update vvp to match iverilog

**Comment by caryr** [comment]
You are compiling using iverilog 10.3, but using the new 13.0 runtime. Make sure both the iverilog ad vvp you are using have the same version and this should work as expected. This check was added to avoid unexpected issues created by using a runtime (vvp) that did not match the compiler expectations.

**Comment by liuyuxivapor** [comment]
urrr... i v found it, cuz i used tmux but did not restart it after updating iverilog and vvp. Thanks!!!
