### ISSUE TITLE
_pli_types.h renamed

### ISSUE THREAD

**Issue by psumesh** [steveicarus/iverilog#866]
_pli_types.h renamed to _pli_types.h.in which cause compile issue in in acc_user.h file

**Comment by steveicarus** [comment]
That is normal and correct. The _pli_types.h file is generated from the _pli_types.h.in file by the "configure" configuration script.

See this section of the build documentation: https://steveicarus.github.io/iverilog/usage/installation.html#compiling-on-linux-unix
