### ISSUE TITLE
Website `http://iverilog.icarus.com/` not working

### ISSUE THREAD

**Issue by chykon** [steveicarus/iverilog#886]
Address <http://iverilog.icarus.com/> redirects to the Google account login screen.

**Comment by Nickellick** [comment]
Still not working, but says that iverilog.com does not exists

**Comment by Freed-Wu** [comment]
Should be <https://steveicarus.github.io>.

**Comment by aelmahmoudy** [comment]
> Should be https://steveicarus.github.io/iverilog/.

Where could I find the release notes ?

**Comment by DeflateAwning** [comment]
This issue can be closed

**Comment by DeflateAwning** [comment]
This issue was fixed in #1011, and can be closed now. All instances of the dead site have been removed in the docs.

**Comment by PoignardAzur** [comment]
You should probably do a sweep online to track down projects linking to the old page, 'cause there are still *a lot*.

**Comment by martinwhitaker** [comment]
OK, it looks like the old website is not coming back, so closing.
