### ISSUE TITLE
undefined pass-by-value error

### ISSUE THREAD

**Issue by cemery123** [steveicarus/iverilog#888]
Hello, we have discovered a perplexing issue during the actual operation of the project. In order to ensure code conciseness, we merged a portion of the inertia delay, which theoretically should not affect the output of the results. This is because simulation characteristics prevent the detection of inertia delay. However, during our actual operation, we found data anomalies in the merged files.

The files with the suffix "_mts" are our original stimulus files, while those without are our merged files. Syn_identity.v is the design file.

I have attached the code output signal results for your reference and verification.
[4.11.zip](https://github.com/steveicarus/iverilog/files/11195833/4.11.zip)

**Comment by martinwhitaker** [comment]
Like #884, I get the same results with another simulator, so again I think this is a race in your code.
