### ISSUE TITLE
Abnormal delay value transmission exception

### ISSUE THREAD

**Issue by cemery123** [steveicarus/iverilog#894]
Hello, we found a potential Iverilog value transfer error. After adding a delay before the signed function, iverilog may experience abnormal delays. In order to ensure the simplicity of the code, we have merged the part of the inertial delay. In theory, this approach will not affect the output of the result. Inertial delay will not be detected due to simulation characteristics. However, during our actual operation, we found that some data abnormalities appeared in some files after merging. Iverilog lost data in 35ns to 40ns
The file with the _mts suffix is our original stimulus file, the one without this is our merged file. Syn_identity.v is the design file
I attach the code to output the signal result for your convenience
[4.16.zip](https://github.com/steveicarus/iverilog/files/11241132/4.16.zip)
![圖片1](https://user-images.githubusercontent.com/63329182/232264977-127702b7-f16e-4582-9313-7c1f56bc0476.png)
![圖片2](https://user-images.githubusercontent.com/63329182/232264979-ee96efc6-5e9e-48e8-a754-cf04df7340df.png)

**Comment by martinwhitaker** [comment]
Like #884, I get the same results with another simulator, so again I think this is a race in your code.
