### ISSUE TITLE
Installation instructions don't explain how to run tests

### ISSUE THREAD

**Issue by yurivict** [steveicarus/iverilog#902]
[here](https://steveicarus.github.io/iverilog/usage/installation.html)

**Comment by martinwhitaker** [comment]
If you mean running your own tests, that's described in the next section of the documentation. If you mean running the compiler regression tests, that's described further on in https://steveicarus.github.io/iverilog/developer/getting_started.html. So I don't understand your complaint.

**Comment by caryr** [comment]
No more information provided so closing this report.
