### ISSUE TITLE
Missing symbols in ivl.def

### ISSUE THREAD

**Issue by pojakobsen** [steveicarus/iverilog#91]
Ran into linking issues w/ cocotb.  3 symbols below were missing for libtool

From 891d2c0a9e8015d05ff9a40df697cca5333d4077 Mon Sep 17 00:00:00 2001
From: Peter Jakobsen <peterojakobsen@yahoo.com>
Date: Sat, 20 Feb 2016 15:39:06 -0700
Subject: [PATCH] Add missing symbols for dlltool to export

---
 ivl.def | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/ivl.def b/ivl.def
index 5622118..5fee414 100644
--- a/ivl.def
+++ b/ivl.def
@@ -211,6 +211,9 @@ ivl_scope_enumerates
 ivl_scope_event
 ivl_scope_events
 ivl_scope_file
+ivl_scope_func_type
+ivl_scope_func_signed
+ivl_scope_func_width
 ivl_scope_is_auto
 ivl_scope_is_cell
 ivl_scope_lineno
-- 
2.7.0

[0001-Add-missing-sympols-for-dlltool-to-export.patch.txt](https://github.com/steveicarus/iverilog/files/139383/0001-Add-missing-sympols-for-dlltool-to-export.patch.txt)

**Comment by steveicarus** [comment]
Applied to git master. You weren't clear on which branch you meant this for, but I remember adding those function to the master branch, so that's where I applied your patch.

Thanks!
