### ISSUE TITLE
Iverilog Possible exception for bit-width pass-by-value in undefined function

### ISSUE THREAD

**Issue by cemery123** [steveicarus/iverilog#920]
Hello, we found an abnormal behavior about Iverilog. During our actual simulation process, we found that iverilog will have an exception in the undefined function of bit width transfer value. We first used vivado to compare and found the exception. After we uploaded the code to edaplayround, the output of comparing Iverilog with GPL is still abnormal. There is a big difference between Iverilog and GPL between 30ps and 40ps. After commenting out the wire4-related signals, the output becomes consistent.
![1683598843790](https://user-images.githubusercontent.com/63329182/236977616-fa0cb3c7-6833-4e55-97ef-5fb80c3ad65e.png)
![1683598851207](https://user-images.githubusercontent.com/63329182/236977619-f26a8d13-9383-4409-8018-c6815b138822.png)
our file in edaplayground is https://edaplayground.com/x/i8h8
Looking forward to your reply

**Comment by martinwhitaker** [comment]
I tested your example with all the simulators available on EDA playground. Every other simulator gives the same output as iverilog. So this is either a bug in GPL Cver or some non-deterministic behaviour in your code.

Closing as invalid.
