### ISSUE TITLE
Running demo on instructions doesn't work when using command file

### ISSUE THREAD

**Issue by IrishMedicalStudent** [steveicarus/iverilog#955]
The demo here (https://steveicarus.github.io/iverilog/usage/getting_started.html#) doesn't appear to work? When the attached files are used and the commands:

`iverilog -o my_design -c File_List.txt`
`vvp my_design`

Are ran, there is no output. Running:

`iverilog -o Counter_TB counter_tb.v counter.v `
`vvp Counter_TB`

Works fine though? The my_design command seems to generate a truncated version of the expected result.

[Samples.zip](https://github.com/steveicarus/iverilog/files/11780293/Samples.zip)

**Comment by caryr** [comment]
What system and version of iverilog are you using? This works as expected on Ubuntu 22.04 using the latest development version of Icarus.

**Comment by hlutor** [comment]
I also experienced weird behavior when using a command file in a similar manner. This was while using the v11-branch on Ubuntu 20.04. Updating to the v12-branch fixed it.

**Comment by caryr** [comment]
No more information provided so closing this report.
