### ISSUE TITLE
vvp: return non-zero exit code on failures

### ISSUE THREAD

**Issue by jleightcap** [steveicarus/iverilog#976]
Currently in some error cases, `vvp` logs an error message but does not flag an error to the shell by returning a non-zero exit code. 
For example, with `$readmemb` (https://github.com/steveicarus/iverilog/blob/master/vpi/sys_readmem.c#L326-L332),

```sh
$ vvp test/alu.tb.vvp 
VCD info: dumpfile alu.tb.vcd opened for output.
(cut)
ERROR: test/alu.tb.gen.v:31: $readmemb: Unable to open test/alu.tv for reading.
(cut)
test/alu.tb.gen.v:60: $finish called at 15 (1s)
$ echo $?
0
```

For use in Makefiles, it would be useful if this error was propagated.

**Comment by ldoolitt** [comment]
Maybe you want vvp -N?
Read the man page.

**Comment by caryr** [comment]
Did the -N flag fix the issue?

**Comment by caryr** [comment]
No reply so closing this report.
