### ISSUE TITLE
configure missing from repository?

### ISSUE THREAD

**Issue by jordankrim** [steveicarus/iverilog#996]
The README.md says to run ./configure to make iverilog but there is no such file in the repository so I am unable to build iverilog.

**Comment by martinwhitaker** [comment]
See the next paragraph in the README.md. If checking out from git, you need to run `sh autoconf.sh` to generate the `configure` file.

Given that these days, most people will be getting the code from GitHub, we maybe should revise the instructions,

**Comment by DeflateAwning** [comment]
Related to #668. This issue can be closed, as #668 addresses these issues.
